AWSTemplateFormatVersion: 2010-09-09
Description: Create a table for Joppin's lock in DynamoDB

Parameters:
  TableName:
    Type: String
    Default: JoppinLockTable
    Description: Lock Table Name

Resources:
  LockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        -
          AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "LockID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
