apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
spec:
  selector:
    app: dynamodb-local
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb-local
  template:
    metadata:
      labels:
        app: dynamodb-local
    spec:
      containers:
      - name: dynamodb-local
        image: amazon/dynamodb-local
        ports:
        - containerPort: 8000
      - name: init-table
        image: madogiwa/joppin-examples-k8s-cronjob-basic
        command: ["sleep", "infinity"]
        env:
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          value: "AKIAIOSFODNN7EXAMPLE"
        - name: AWS_SECRET_ACCESS_KEY
          value: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                curl -s -L https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- localhost:8000 -- sleep 1
                aws dynamodb create-table --endpoint-url http://localhost:8000 \
                  --table-name JoppinLockTable \
                  --attribute-definitions \
                    AttributeName=LockID,AttributeType=S \
                  --key-schema \
                    AttributeName=LockID,KeyType=HASH \
                  --provisioned-throughput \
                    ReadCapacityUnits=10,WriteCapacityUnits=5
